"""
pi_agent — Agent loop and state management
Python mirror of @mariozechner/pi-agent-core / @earendil-works/pi-agent-core
"""

from pi_ai import stream_simple

from .stream_fn import get_default_stream_fn, set_default_stream_fn

# Hosts can override this. Installing stream_simple keeps existing Python
# callers working when they omit stream_fn (coding-agent, tests).
set_default_stream_fn(stream_simple)

from .agent import Agent, AgentOptions
from .agent_loop import (
    agent_loop,
    agent_loop_continue,
    run_agent_loop,
    run_agent_loop_continue,
)
from .proxy import stream_proxy
from .search import create_scanning_session_search, scanning_entries
from .harness import (  # noqa: E402
    AGENT_TELEMETRY_SCHEMAS,
    AI_TELEMETRY_SCHEMA,
    HARNESS_TELEMETRY_SCHEMA,
    NOOP_TELEMETRY_CONTEXT,
    AgentHarness,
    AgentHarnessOptions,
    AgentHarnessResources,
    CompactResult,
    ExecutionEnv,
    ExecutionToolContext,
    FileError,
    FileInfo,
    HarnessClosed,
    HarnessNotImplemented,
    HarnessTool,
    InMemorySessionRepo,
    InMemorySessionStorage,
    JsonlSessionRepo,
    JsonlSessionStorage,
    NodeExecutionEnv,
    PromptTemplate,
    PythonExecutionEnv,
    Result,
    Session,
    Skill,
    compact,
    convert_to_llm,
    create_bash_tool,
    create_edit_tool,
    create_python_execution_env,
    create_read_tool,
    create_write_tool,
    err,
    format_prompt_template_invocation,
    format_skill_invocation,
    format_skills_for_system_prompt,
    get_or_throw,
    get_or_undefined,
    load_prompt_templates,
    load_skills,
    ok,
    should_compact,
    start_ai_span,
    start_harness_span,
    truncate_head,
    truncate_tail,
)
from .types import (
    AfterToolCallContext,
    AfterToolCallResult,
    AgentContext,
    AgentEvent,
    AgentEventAgentEnd,
    AgentEventAgentStart,
    AgentEventMessageEnd,
    AgentEventMessageStart,
    AgentEventMessageUpdate,
    AgentEventToolEnd,
    AgentEventToolStart,
    AgentEventToolUpdate,
    AgentEventTurnEnd,
    AgentEventTurnStart,
    AgentLoopConfig,
    AgentLoopTurnUpdate,
    AgentMessage,
    AgentState,
    AgentTool,
    AgentToolCall,
    AgentToolResult,
    AgentToolUpdateCallback,
    BeforeToolCallContext,
    BeforeToolCallResult,
    CustomAgentMessages,
    PrepareNextTurnContext,
    QueueMode,
    ShouldStopAfterTurnContext,
    StreamFn,
    ThinkingLevel,
    ToolExecutionMode,
)

__all__ = [
    # Agent class
    "Agent",
    "AgentOptions",
    # Loop functions
    "agent_loop",
    "agent_loop_continue",
    "run_agent_loop",
    "run_agent_loop_continue",
    # Stream defaults
    "set_default_stream_fn",
    "get_default_stream_fn",
    # Proxy
    "stream_proxy",
    # Types
    "AfterToolCallContext",
    "AfterToolCallResult",
    "AgentContext",
    "AgentEvent",
    "AgentEventAgentEnd",
    "AgentEventAgentStart",
    "AgentEventMessageEnd",
    "AgentEventMessageStart",
    "AgentEventMessageUpdate",
    "AgentEventToolEnd",
    "AgentEventToolStart",
    "AgentEventToolUpdate",
    "AgentEventTurnEnd",
    "AgentEventTurnStart",
    "AgentLoopConfig",
    "AgentLoopTurnUpdate",
    "AgentMessage",
    "AgentState",
    "AgentTool",
    "AgentToolCall",
    "AgentToolResult",
    "AgentToolUpdateCallback",
    "BeforeToolCallContext",
    "BeforeToolCallResult",
    "CustomAgentMessages",
    "PrepareNextTurnContext",
    "QueueMode",
    "ShouldStopAfterTurnContext",
    "StreamFn",
    "ThinkingLevel",
    "ToolExecutionMode",
    # Harness
    "AGENT_TELEMETRY_SCHEMAS",
    "AI_TELEMETRY_SCHEMA",
    "HARNESS_TELEMETRY_SCHEMA",
    "NOOP_TELEMETRY_CONTEXT",
    "AgentHarness",
    "AgentHarnessOptions",
    "AgentHarnessResources",
    "CompactResult",
    "ExecutionEnv",
    "ExecutionToolContext",
    "FileError",
    "FileInfo",
    "HarnessClosed",
    "HarnessNotImplemented",
    "HarnessTool",
    "InMemorySessionRepo",
    "InMemorySessionStorage",
    "JsonlSessionRepo",
    "JsonlSessionStorage",
    "NodeExecutionEnv",
    "PromptTemplate",
    "PythonExecutionEnv",
    "Result",
    "Session",
    "Skill",
    "compact",
    "convert_to_llm",
    "create_bash_tool",
    "create_edit_tool",
    "create_python_execution_env",
    "create_read_tool",
    "create_write_tool",
    "create_scanning_session_search",
    "err",
    "format_prompt_template_invocation",
    "format_skill_invocation",
    "format_skills_for_system_prompt",
    "get_or_throw",
    "get_or_undefined",
    "load_prompt_templates",
    "load_skills",
    "ok",
    "scanning_entries",
    "should_compact",
    "start_ai_span",
    "start_harness_span",
    "truncate_head",
    "truncate_tail",
]
