from .context import (
    SessionContext,
    SessionContextBuildOptions,
    build_context_entries,
    build_session_context,
    default_context_entry_transform,
    session_entry_to_context_messages,
)
from .jsonl import (
    JsonlSessionCreateOptions,
    JsonlSessionListOptions,
    JsonlSessionMetadata,
    JsonlSessionRepo,
    JsonlSessionRepoOptions,
    JsonlSessionStorage,
    JsonlV4Header,
)
from .memory import InMemorySessionRepo, InMemorySessionStorage
from .session import Session, assert_json_serializable
from .testing import (
    SessionBackendConformanceCase,
    SessionBackendFixture,
    SessionBackendFixtureFactory,
    SessionFixture,
    SimpleSessionBackendFixture,
    create_session_backend_conformance,
    run_storage_conformance,
)
from .types import (
    Entry,
    EntryQuery,
    ForkOptions,
    JsonValue,
    LanePointer,
    LaneRecord,
    LogItem,
    NewRecord,
    OperationStartedRecord,
    ProvisionedEntry,
    RecordQuery,
    SessionCreateOptions,
    SessionError,
    SessionMetadata,
    SessionStats,
)

# SessionTree is documented in TS as an interface; Python uses Session / view objects.
SessionTree = Session

__all__ = [
    "SessionContext",
    "SessionContextBuildOptions",
    "build_context_entries",
    "build_session_context",
    "default_context_entry_transform",
    "session_entry_to_context_messages",
    "JsonlSessionCreateOptions",
    "JsonlSessionListOptions",
    "JsonlSessionMetadata",
    "JsonlSessionRepo",
    "JsonlSessionStorage",
    "JsonlSessionRepoOptions",
    "JsonlV4Header",
    "InMemorySessionRepo",
    "InMemorySessionStorage",
    "Session",
    "assert_json_serializable",
    "Entry",
    "EntryQuery",
    "ForkOptions",
    "JsonValue",
    "LanePointer",
    "LaneRecord",
    "LogItem",
    "NewRecord",
    "OperationStartedRecord",
    "ProvisionedEntry",
    "RecordQuery",
    "SessionCreateOptions",
    "SessionError",
    "SessionMetadata",
    "SessionStats",
    "SessionTree",
    "SessionBackendConformanceCase",
    "SessionBackendFixture",
    "SessionBackendFixtureFactory",
    "SessionFixture",
    "SimpleSessionBackendFixture",
    "create_session_backend_conformance",
    "run_storage_conformance",
]
