"""
pi_tui — Terminal User Interface library with differential rendering.

Python port of @mariozechner/pi-tui (TypeScript).
"""
from .autocomplete import (
    ApplyResult,
    AutocompleteItem,
    AutocompleteProvider,
    CombinedAutocompleteProvider,
    SlashCommand,
    SuggestionResult,
)
from .components import (
    Box,
    CancellableLoader,
    DefaultTextStyle,
    Editor,
    EditorOptions,
    EditorTheme,
    HStack,
    Image,
    ImageOptions,
    ImageTheme,
    Input,
    Loader,
    LoaderIndicatorOptions,
    Markdown,
    MarkdownOptions,
    MarkdownTheme,
    SelectItem,
    SelectList,
    SelectListLayoutOptions,
    SelectListTheme,
    ScrollView,
    ScrollViewOptions,
    ScrollViewScrollToOptions,
    ScrollViewScrollbar,
    SelectListTruncatePrimaryContext,
    SettingItem,
    SettingsList,
    SettingsListOptions,
    SettingsListTheme,
    Spacer,
    Stack,
    StackEntry,
    Text,
    TextChunk,
    TruncatedText,
    VStack,
    word_wrap_line,
)
from .editor_component import EditorComponent
from .fuzzy import fuzzy_filter, fuzzy_match
from .keybindings import (
    DEFAULT_EDITOR_KEYBINDINGS,
    TUI_KEYBINDINGS,
    EditorAction,
    EditorKeybindingsManager,
    KeybindingConflict,
    KeybindingDefinition,
    KeybindingsManager,
    get_editor_keybindings,
    get_keybindings,
    set_editor_keybindings,
    set_keybindings,
)
from .keys import (
    KEY,
    decode_kitty_printable,
    is_key_release,
    is_key_repeat,
    is_kitty_protocol_active,
    matches_key,
    parse_key,
    set_kitty_protocol_active,
)
from .kill_ring import KillRing
from .latex import RenderLatexOptions, render_latex
from .stdin_buffer import StdinBuffer
from .terminal import ProcessTerminal, Terminal, resolve_escape_timeout_ms
from .terminal_colors import (
    RgbColor,
    TerminalColorScheme,
    parse_osc11_background_color,
    parse_terminal_color_scheme_report,
)
from .terminal_image import (
    CellDimensions,
    ImageDimensions,
    ImageRenderOptions,
    KittyImageMetadata,
    KittyImagePlacement,
    TerminalCapabilities,
    allocate_image_id,
    crop_kitty_image_line,
    delete_all_kitty_images,
    delete_all_kitty_placements,
    delete_kitty_image,
    get_capabilities,
    get_cell_dimensions,
    get_image_dimensions,
    get_kitty_image_metadata,
    get_kitty_image_placement,
    hyperlink,
    image_fallback,
    is_image_line,
    register_kitty_image_metadata,
    render_image,
    set_capabilities,
)
from .alt_screen_search import (
    AltScreenSearchComponent,
    AltScreenSearchMatch,
    find_alt_screen_search_matches,
)
from .layout import LayoutFrame, LayoutRect, render_layout_frame
from .native_modifiers import is_native_modifier_pressed
from .tui import (
    CURSOR_MARKER,
    TUI,
    Container,
    OverlayHandle,
    OverlayOptions,
    OverlayUnfocusOptions,
    TuiMode,
    TuiStopOptions,
    composite_tui_line,
    is_viewport_tui,
)
from .tui_alt_screen import TuiAltScreen, TuiAltScreenOptions
from .tui_main_screen import TuiMainScreen, TuiMainScreenRenderState
from .undo_stack import UndoStack
from .utils import (
    AnsiCodeTracker,
    PUNCTUATION_REGEX,
    apply_background_to_line,
    extract_ansi_code,
    extract_segments,
    get_osc8_link_at_column,
    is_punctuation_char,
    is_whitespace_char,
    normalize_terminal_output,
    slice_by_column,
    slice_with_width,
    strip_terminal_sequences,
    truncate_to_width,
    visible_width,
    wrap_text_with_ansi,
)
from .word_navigation import find_word_backward, find_word_forward

__all__ = [
    # autocomplete
    "ApplyResult",
    "AutocompleteItem",
    "AutocompleteProvider",
    "CombinedAutocompleteProvider",
    "SlashCommand",
    "SuggestionResult",
    # components
    "Box",
    "CancellableLoader",
    "DefaultTextStyle",
    "Editor",
    "EditorOptions",
    "EditorTheme",
    "HStack",
    "Image",
    "ImageOptions",
    "ImageTheme",
    "Input",
    "Loader",
    "LoaderIndicatorOptions",
    "Markdown",
    "MarkdownOptions",
    "MarkdownTheme",
    "SelectItem",
    "SelectList",
    "SelectListLayoutOptions",
    "ScrollView",
    "ScrollViewOptions",
    "ScrollViewScrollToOptions",
    "ScrollViewScrollbar",
    "SelectListTheme",
    "SelectListTruncatePrimaryContext",
    "SettingItem",
    "SettingsList",
    "SettingsListOptions",
    "SettingsListTheme",
    "Spacer",
    "Stack",
    "StackEntry",
    "Text",
    "TextChunk",
    "TruncatedText",
    "VStack",
    "word_wrap_line",
    # editor component protocol
    "EditorComponent",
    # fuzzy
    "fuzzy_filter",
    "fuzzy_match",
    # keybindings
    "DEFAULT_EDITOR_KEYBINDINGS",
    "EditorAction",
    "EditorKeybindingsManager",
    "KeybindingConflict",
    "KeybindingDefinition",
    "KeybindingsManager",
    "TUI_KEYBINDINGS",
    "get_editor_keybindings",
    "get_keybindings",
    "set_editor_keybindings",
    "set_keybindings",
    # keys
    "KEY",
    "decode_kitty_printable",
    "is_key_release",
    "is_key_repeat",
    "is_kitty_protocol_active",
    "matches_key",
    "parse_key",
    "set_kitty_protocol_active",
    # kill ring
    "KillRing",
    # latex
    "RenderLatexOptions",
    "render_latex",
    # stdin buffer
    "StdinBuffer",
    # terminal
    "ProcessTerminal",
    "Terminal",
    "resolve_escape_timeout_ms",
    # terminal colors
    "RgbColor",
    "TerminalColorScheme",
    "parse_osc11_background_color",
    "parse_terminal_color_scheme_report",
    # terminal image
    "CellDimensions",
    "ImageDimensions",
    "ImageRenderOptions",
    "TerminalCapabilities",
    "get_capabilities",
    "get_cell_dimensions",
    "get_image_dimensions",
    "hyperlink",
    "image_fallback",
    "is_image_line",
    "render_image",
    "set_capabilities",
    "KittyImageMetadata",
    "KittyImagePlacement",
    "allocate_image_id",
    "crop_kitty_image_line",
    "delete_all_kitty_images",
    "delete_all_kitty_placements",
    "delete_kitty_image",
    "get_kitty_image_metadata",
    "get_kitty_image_placement",
    "register_kitty_image_metadata",
    # tui
    "CURSOR_MARKER",
    "OverlayHandle",
    "OverlayOptions",
    "OverlayUnfocusOptions",
    "TUI",
    "Container",
    "TuiMode",
    "TuiStopOptions",
    "composite_tui_line",
    "is_viewport_tui",
    # undo stack
    "UndoStack",
    # utils
    "AnsiCodeTracker",
    "PUNCTUATION_REGEX",
    "apply_background_to_line",
    "extract_ansi_code",
    "extract_segments",
    "get_osc8_link_at_column",
    "is_punctuation_char",
    "is_whitespace_char",
    "normalize_terminal_output",
    "slice_by_column",
    "slice_with_width",
    "strip_terminal_sequences",
    "truncate_to_width",
    "visible_width",
    "wrap_text_with_ansi",
    # word navigation
    "find_word_backward",
    "find_word_forward",
    "AltScreenSearchComponent",
    "AltScreenSearchMatch",
    "LayoutFrame",
    "LayoutRect",
    "TuiAltScreen",
    "TuiAltScreenOptions",
    "TuiMainScreen",
    "TuiMainScreenRenderState",
    "find_alt_screen_search_matches",
    "is_native_modifier_pressed",
    "render_layout_frame",
]
